### PR TITLE
TEC-730: Move search bar to hamburger, add "subscribe" call to action

### PR DESCRIPTION
**Pull request by fabiosantoscode**
This also features some refactoring. "Search" and "Log in" are now treated as a kind of `navigation__main-navigation-link`, `navigation__main-navigation-link-icon` and have their own microcomponent.

Can be seen in the wild, wild web in http://frutal.pt/component-navigation/

### CODE REVIEW

**Comment by umbobabo** [comment]
Mhmhmh...tested on Chrome.

screen shot 2016-04-21 at 10 41 15

**Comment by fabiosantoscode** [comment]
It's a component-google-search bug which happens when you have several search boxes. I've fixed that in component-google-search. You probably still have the old version! Or, god forbid, `npm link`!

**Comment by umbobabo** [comment]
Quite strange due to the fact that I used your link http://frutal.pt/component-navigation/ LOL

**Comment by fabiosantoscode** [comment]
LOL stupid chrome, have to test again

**Comment by fabiosantoscode** [comment]
Lol! Tests were creating `<Navigation>` elements with the same IDs and calling into the google API.

**Comment by umbobabo** [comment]
screen shot 2016-04-22 at 11 29 47

screen shot 2016-04-22 at 11 30 27

**Comment by fabiosantoscode** [comment]
> DK ->> [image]

Just like before.

> Mobile ->> [image]

This is because link-button's color was unset. It will be set in fe-blogs, so no need to set it here.

**Pull request merged**
