### PR TITLE
WIP! slot based nav

### PR DESCRIPTION
**Pull request by keithamus**
Similar to refactoring the accordion (https://github.com/economist-components/component-accordion/pull/135) I've also refactored this nav, as part of a story on making it more flexible for world-if.

This PR removes a lot of existing code, in favour of... you guessed it, SLOTS! Currently, the existing code to instantiate looks like this:

```js
import React from 'react';
import Navigation from '@economist/component-navigation';
export default (
  <Navigation
    className="myNav"
    svgUri="assets/icons.svg"
    sectionsCardData={navigationLinks}
    moreBalloonData={moreBalloonData}
    accordionData={accordionContext}
    sharedMenu={sharedMenu}
  />
);
```

The problem here, is that the API is super opaque, and also forces certain parts of the nav to be adhered to. A non-exhaustive list of issues with the above:

 - The logo is a fixed asset, we can only supply the `svgUri`.
 - What if I dont want the logo?
 - What if I want to do something interesting like switching the logo at different breakpoints?
 - `svgUri` is a completely un-indicative name for defining the logo svg
 - Wtf is `sectionsCardData` and how does it relate to a nav?
 - Wtf is `moreBalloonData` and how does it relate to a nav?
 - Wtf is `accordionData` and how does it relate to a nav?
 - Wtf is `sharedMenu` and how does it relate to a nav?
 - Are any of these opt out? Or does the nav fall flat when I omit them (hint: the latter).
 - How can I customise any of these above objects for my particular usecase?
 - How can I add additional customisations to this nav?
 - The nav is implicitly sticky with no way to turn this off.
 - Whole menus are generated inside of the nav (see: usermenu) and can't be turned off. There's no real reason why they're in here and not as a separate component.

So what should a navigation actually give us? Or more precisely, what can it give us that we couldn't do easily on our own?

Here is the proposal for a new (slot based) API:

```js
import React from 'react';
import Navigation from '@economist/component-navigation';
import { Accordion, Panel } from '@economist/component-accordion';
import { Search } from '@economist/component-google-search';
export default (
  <Navigation
    className="myNav"
    logo={<img src="assets/icons.svg#logo" />}
    menu={
      <Accordion>
        <Panel header="Topics">
          <ul><li>Latest Updates</li></ul>
          ...
        </Panel>
        <a>Latest Updates</a>
        <Panel header="More">
          <ul><li>Apps and Digital Editions</li></ul>
          ...
        </Panel>
      </Accordion>
    }
  >
    <button>Subscribe</button>
    <Accordion>
      <Panel header="Log In">
      </Panel>
    </Accordion>
    <Search/>
  </Navigation>
);
```

What makes this API "better"?

 - The `logo` prop does what it says, it provides markup for a logo element (including schema.org props)
 - If you dont want the logo, omit it and the markup disappears
 - The `menu` prop does what it says, it provides the markup for a menu (with schema.org props)
 - Don't want the `menu`? Omit it and the markup disappears
 - Menu can be accordions, ul, or anything you really want it to be. Maximum flexibility
 - Rather than having generated objects which half mimick the React API, you can pass in actual React elements to the menu, making it much more flexible and more standardised
 - Children can be passed in, and fill up the `navigation__extra` panel, which allows for custom branding or additional non-main-menu links. Dealer's choice.
 - This means at the minimum set `<Navigation/>` basically just renders `<header role="banner" class="navigation" itemScope itemType="http://schema.org/WPHeader"/>`. However the full set provides rich markup _where it is relevant and easy to supply_.
 - For the sake of simplicitly, the navigation has nothing to do with Sticky. Want a sticky nav? `<Sticky><Navigation/></Sticky>` will work :smile:
 - This doesn't feature any non-opt-out parts, like the user-menu. We can take the usermenu code and put it in a new component, if needs be.

### What next?

Let's discuss this further, see what people feel about this change. It fits the spec of being more flexible for world-if, but we should consider if we sacrifice to much for existing sites.

### CODE REVIEW

**Comment by danielmoll** [comment]
Looks good to me, only concern from World If point of view is the time it'll take to get have this as per the current one in looks and functionality.

**Comment by keithamus** [comment]
The two main missing parts from this that are in the old code are:

 - The main menu - actually this is data driven from a JSON blob on feblogs, so it should be a case of pulling out the CSS from here and putting it into feblogs of WIF.
 - The user menu - this was hardcoded inside of the old nav code. I think after greenlighting this PR, we can spend a little while pulling out the usermenu from the old codebase and turning it into a component - making it a drop in piece to replicate the old functionality.

So really I feel as though this is just a case of moving stuff around, and a small piece of refactoring work.

**Comment by danielmoll** [comment]
Okie dokie. Just tests to complete on this then or any further work to the component?

**Comment by keithamus** [comment]
If everyone is happy I'll do the tests and we can merge.

**Comment by fabiosantoscode** [comment]
I'm happy.

We should also start making our menus Relay/graphQL-driven. We shouldn't be updating our menus in code.

**Comment by keithamus** [comment]
Tests are done and should pass. Once they've passed if everyone is happy, can we merge please?

**Comment by danielmoll** [comment]
Right, LGTM, I'll merge and lets get this in a real working situation with the World If 😬

**Pull request merged**
